#-------------------------------------
# module.security \u6A21\u5757\u521D\u59CB\u5316\u53C2\u6570
#-------------------------------------

# \u6A21\u5757\u662F\u5426\u5DF2\u542F\u7528, \u9ED8\u8BA4\u503C: true
#ymp.configs.module.security.enabled=false

# \u7F13\u5B58\u540D\u79F0\u524D\u7F00, \u9ED8\u8BA4\u503C: ""
ymp.configs.module.security.cache_name_prefix=

# \u7F13\u5B58\u6570\u636E\u8D85\u65F6\u65F6\u95F4, \u53EF\u9009\u53C2\u6570, \u6570\u503C\u5FC5\u987B\u5927\u4E8E\u7B49\u4E8E0, \u5426\u5219\u5C06\u91C7\u7528\u9ED8\u8BA4
ymp.configs.module.security.cache_timeout=

# \u7528\u6237\u8BA4\u8BC1\u5DE5\u5382, \u9ED8\u8BA4\u503C: net.ymate.module.security.impl.DefaultAuthenticatorFactory
ymp.configs.module.security.authenticator_factory_class=